apiVersion: v1
kind: Service
metadata:
  name: om
  namespace: default
spec:
  clusterIP: None
  clusterIPs:
  - None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: ui
    port: 9874
    protocol: TCP
    targetPort: 9874
  - name: ipc
    port: 9862
    protocol: TCP
    targetPort: 9862
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Endpoints
metadata:
  labels:
    service.kubernetes.io/headless: ""
  name: om
  namespace: default
subsets:
- addresses:
  - hostname: om-0
    ip: VM1
  ports:
  - name: ipc
    port: 9862
    protocol: TCP
  - name: ui
    port: 9874
    protocol: TCP
---
